---
name: Lucas
surname: Johnson, Ph.D.
# position: "Ph.D. Candidate"
# address: "State University of New York College of Environmental Science and Forestry"
phone: +1 315-345-4713
www: lucaskjohnson.com
email: lucas.k.johnson03@gmail.com
github: lucas-johnson
linkedin: lucaskjohnson
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::moderncv:
    theme: banking
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Details,
    "Doctor of Philosophy in Environmental Science", "Aug 2019 - May 2024", "State University College of Environmental Science and Forestry", "Syracuse, New York", "Dissertation: \\textit{Mapping forest aboveground biomass stocks and changes to facilitate natural climate solutions in New York State}",
  "Bachelor of Science in Computer Science", "Aug 2013 - May 2017", "Tufts University", "Boston, Massachusetts", NA

) %>% 
  detailed_entries(Degree, Year, Institution, Where, Details, .protect = FALSE)
```

# Publications

## In Review

```{r eval = TRUE}
tribble(
  ~ When, ~ BeforeYou, ~ You, ~ AfterYou, ~ Title, ~ Details, ~ url,
  "2023", "Mahoney, M.J., ", "Johnson, L.K.,", "Silge, J., Frick, H., Kuhn, M., and Beier, C. M.", "Assessing the performance of spatial cross-validation approaches for models of spatially structured data.", "In review at Environmental Modelling \\& Software", "https://doi.org/10.48550/arXiv.2303.07334",
  ) %>% 
  brief_entries(glue::glue("<BeforeYou>\\textbf{<You>} <AfterYou> <Title> <Details>. \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```


## Peer-Reviewed Journal Articles

```{r}
tribble(
  ~ When, ~ BeforeYou, ~ You, ~ AfterYou, ~ Title, ~ Details, ~ url,
    "2025", "", "Johnson, L. K.,", "Domke, G. M., Stehman, S. V., Mahoney, M. J., Beier, C. M.", "From pixels to parcels: flexible practical small-area uncertainty estimation for spatial averages obtained from aboveground biomass maps.", "Remote Sensing of Environment, 330, 114951", "https://doi.org/10.1016/j.rse.2025.114951",
  "2025", "", "Johnson, L. K.,", "Yang, Z., Erb, A., Bright, R. M., Domke, G. M., Frescino, T. S., Schaaf, C. B., Healey, S. P.", "Integrating albedo offsets in reforestation decisions for climate change mitigation outcomes in 2050: a case study in the USA.", "Forest Ecology and Management, 587, 122699", "https://doi.org/10.1016/j.foreco.2025.122699",
  "2025", "", "Johnson, L. K.,", "Mahoney, M. J., Domke, G. M., and Beier, C. M.", "New allometric models for the USA create a shift in forest carbon estimation, modeling, and mapping.", "Forest Ecology and Management, 589, 122751", "https://doi.org/10.1016/j.foreco.2025.122751",
  "2025", "Desrochers, M. L., Clippard, E. A., ", "Johnson, L. K.,", "and Beier, C. M. 2024.", "Declining trends in canopy disturbance across reserve forest landscapes of the northeastern US.", "Forest Ecology and Management, 578, 122463", "https://doi.org/10.1016/j.foreco.2024.122463",
  "2024", "Cranmer, N., Han, T., Chedzoy, B., Smallidge, P. J., Beier, C. M., ", "Johnson, L. K.,", "and Xu, X. 2024.", "Estimating merchantable and non-merchantable wood volume in slash walls using terrestrial and airborne LiDAR.", "Forest Ecology and Management, 569, 122211", "https://doi.org/10.1016/j.foreco.2024.122211",
  "2023", "", "Johnson, L. K.,", "Mahoney, M. J., Desrochers, M. L., and Beier, C. M. 2023.", "Mapping historical forest biomass for stock-change assessments at parcel to landscape scales.", "Forest Ecology and Management, 546, 121348", "https://doi.org/10.1016/j.foreco.2023.121348",
  "2022", "Desrochers, M. L., Tripp, W., Logan, S., Bevilacqua, E., ", "Johnson, L.K.,", "and Beier, C. M. 2022.", "Ground-Truthing Forest Change Detection Algorithms in Working Forests of the US Northeast.", "Journal of Forestry, 120(5), 575–587", "https://doi.org/10.1093/jofore/fvab075",
  "2022", "", "Johnson, L. K.,", "Mahoney, M. J., Bevilacqua, E., Stehman, S. V., Domke, G. M., and Beier, C. M. 2022.", "Fine-resolution landscape-scale biomass mapping using a spatiotemporal patchwork of LiDAR coverages.", "The International Journal of Applied Earth Observation and Geoinformation, 114, 103059", "https://doi.org/10.1016/j.jag.2022.103059",
  "2022", "Mahoney, M. J., ", "Johnson, L. K.,", "Guinan, A. Z., and Beier, C. M. 2022.", "Classification and mapping of low-statured 'shrubland' cover types in post-agricultural landscapes of the US Northeast.", "The International Journal of Remote Sensing, 43(19-24), 7117-7138", "https://doi.org/10.1080/01431161.2022.2155086",
  "2022", "Mahoney, M. J., ", "Johnson, L. K.,", "Bevilacqua, E., and Beier, C. M. 2022.", "Ground noise filtering produces inferior models of forest aboveground biomass.", "GIScience and Remote Sensing, 59(1), 1266-1280", "https://doi.org/10.1080/15481603.2022.2103069",

) %>% 
  brief_entries(glue::glue("<BeforeYou>\\textbf{<You>} <AfterYou> <Title> <Details>. \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```


## Peer-Reviewed Book Chapters

```{r}
tribble(
  ~ When, ~ BeforeYou, ~ You, ~ AfterYou, ~ Title, ~ Details, ~ url,
    "2023", "Mahoney, M. J., ", "Johnson, L. K.,", "and Beier, C. M. 2023.", "AI for Shrubland Identification and Mapping.", "In Sun Z, Cristea N, Rivas P (eds.), Artificial Intelligence in Earth Science, 295-316. Elsevier. ISBN 978-0-323-91737-7.", "https://doi.org/10.1016/B978-0-323-91737-7.00010-4",
) %>% 
  brief_entries(glue::glue("<BeforeYou>\\textbf{<You>} <AfterYou> <Title> <Details> \\url{<url>}", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Awards and Honors

```{r}
tribble(
  ~ When, ~ Title, ~ Institution, 
  "2024", "Outstanding PhD Scholar",  "SUNY ESF Division of Environmental Science"
) %>% 
  brief_entries(glue::glue("\\textbf{<Title>} - <Institution>", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Conference Activity

## Invited Talks
```{r}
library(tibble)
tribble(
  ~ Year, ~ BeforeMe, ~ Me, ~ AfterMe , ~ Title, ~ Details,
  "2024", "", "Johnson, L.K., ", "Mahoney, M.J., Domke, G.M., and Beier, C.M.", "New allometric models for the USA create a step-change in forest carbon estimation, modeling, and mapping.", "FIA Science Symposium (Virtual)",
  "2022", "", "Johnson, L.K., ", "Mahoney, M.J., and Beier, C.M.", "Historical Time Series Biomass Modeling: To Train on Plots or Pixels?", "FIA Science Stakeholder Meeting (Virtual)",

) %>% 
  brief_entries(glue::glue("<BeforeMe>\\textbf{<Me>} <AfterMe> <Title> <Details>", 
                           .open = "<", 
                           .close = ">"), 
                Year, 
                .protect = FALSE)
```

## Contributed Talks
```{r}
library(tibble)
tribble(
  ~ Year, ~ BeforeMe, ~ Me, ~ AfterMe , ~ Title, ~ Details,
  "2024", "", "Johnson, L.K., ", "Yang, Z., Erb, A., Domke, G.M., Frescino, T.S., Schaaf, C.B., and Healey, S.P.", "Integrating albedo offsets in reforestation decisions for climate mitigation outcomes in 2050: a case study in the USA.", "FIA Science Symposium (Virtual)",
  "2023", "Mahoney, M. J., ", "Johnson, L. K., ", "and Beier, C. M.", "Consistent Workflows for Assessing Model Performance: Tools and Applications to Natural Climate Solutions.", "American Geophysical Union Fall Meeting, San Francisco, CA",
  "2023", "Beier, C.M., ", "Johnson, L.K., ", "Mahoney, M.J., Desrochers, M.L, and Domke, G.M.", "An integrated carbon monitoring framework for stock-change GHG inventory at parcel to landscape scales: approach, outputs and applications.", "American Geophysical Union Fall Meeting, San Francisco, CA",
  "2022", "", "Johnson, L.K., ", "Mahoney, M.J., and Beier, C.M.", "A Map-based Stock Change Approach for Fine-scale Biomass and Carbon Accounting in NYS.", "Forest Ecosystem Monitoring Cooperateive Conference, Burlington, VT",
  "2022", "", "Johnson, L.K., ", "Mahoney, M.J., and Beier, C.M.", "Historical Time Series Biomass Modeling: To Train on Plots or Pixels?", "American Geophysical Union Fall Meeting (Virtual)",
  "2022", "Mahoney, M.J., ", "Johnson, L.K., ", "and Beier, C.M.", "Detecting regenerating forestland at a landscape level.", "Ecological Society of America and Canadian Society for Ecology and Evolution Joint Annual Meeting, Montreal, Quebec, Canada",
  "2022", "", "Johnson, L.K., ", "Mahoney, M.J., Bevilacqua, E., and Beier, C.M.", "Filtering ground noise from LiDAR returns produces inferior models of forest aboveground biomass", "North American Forest Ecology Workshop, Sault Ste Marie, Ontario (Virtual)",
  "2021", "", "Johnson, L.K., ", "Mahoney, M.J., Bevilacqua, E., and Beier, C.M.", "Broad-scale forest biomass mapping: generating contiguous high-resolution predictions using a spatio-temporal patchwork of LiDAR coverages across a mixed-use landscape.", "American Geophysical Union Fall Meeting (Virtual)",
  "2021", "", "Johnson, L.K., ", "Mahoney, M.J., and Beier, C.M.", "Greening Up Before Growing Up: Challenges in Modeling Forest Biomass Recovery Post-Harvest Using Satellite Imagery.", "Society of American Foresters National Convention (Virtual)",
) %>% 
  brief_entries(glue::glue("<BeforeMe>\\textbf{<Me>} <AfterMe> <Title> <Details>", 
                           .open = "<", 
                           .close = ">"), 
                Year, 
                .protect = FALSE)
```

## Poster Presentations
```{r}
tribble(
  ~ Year, ~ BeforeMe, ~ Me, ~ AfterMe , ~ Title, ~ Details,
  "2023", "", "Johnson, L.K., ", "Mahoney M.J., Domke, G.M., and Beier, C.M.", "Bridging the Gap Between Pixels and Minimum Estimation Units: Small-Area Uncertainty Estimation with Forest Aboveground Biomass Maps.", "American Geophysical Union Fall Meeting, San Francisco, CA"
) %>% 
  brief_entries(glue::glue("<BeforeMe>\\textbf{<Me>} <AfterMe> <Title> <Details>", 
                           .open = "<", 
                           .close = ">"), 
                Year, 
                .protect = FALSE)

```


# Experience

```{r}
tribble(
  ~ When, ~ Group, ~ Details,
  "2024 - Present", "Oregon State University", "\\textbf{Postdoctoral Scholar}. Investigating how surface albedo change resulting from forest growth, reforestation, and afforestation impact decisions around forest management for climate mitigation. Assisting in operationalizing forest carbon reporting tools that leverage data from NASA’s GEDI mission",
  "2019 - 2024", "Climate and Applied Forest Research Institute (SUNY ESF)", "\\textbf{Research Assistant}. Developed cloud computing infrastructure, geospatial databases, and data sharing software. Contributed writing, code, and statistical/spatial analysis to technical reports",
  "2017 - 2019", "Lightkeeper, LLC", "\\textbf{Data Engineer}. Developed internal data management tools and software in python", 
) %>% 
  brief_entries(glue::glue(" \\textbf{<Group>} \\newline{} <Details>",
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Service to the Profession
```{r}
tribble(
  ~ When, ~ Title, ~ Details,
  "2024", "Reviewer:", "Carbon Balance and Management",
  "2023", "Reviewer:", "Forest Ecology and Management, Journal of Applied Earth Observation and Geoinformation, PNAS Nexus",
  "2023", "Workshop Assistant:", "Foundations of Scientific Computing at SUNY ESF",
  "2022", "Workshop Assistant:", "Foundations of Scientific Computing at SUNY ESF"
) %>% 
  brief_entries(glue::glue("\\textbf{<Title>} <Details>", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Community Service

```{r}
# Community Involvement/Outreach. [Optional.]  This includes work with libraries and schools, public lectures, etc.
tribble(
  ~ When, ~ Group, ~ Role, ~ Details,
  "July 2020 - July 2021", "Code for Burlington - Courtbot Project", 
  "Technical Lead (Volunteer)", 
  "A free service providing text message notifications for court appearances"
) %>% 
  brief_entries(glue::glue(" \\textbf{<Group>} <Role>. \\newline{} <Details>",
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Affiliations

```{r}
tribble(
  ~ When, ~ What, ~Who,
  "2021 - Present", "American Geophysical Union", "Member",
  "2021 - Present", "NYS GIS Association", "Member",
) %>% 
  brief_entries(glue::glue("\\textbf{<What>}. <Who>", 
                           .open = "<", 
                           .close = ">"), 
                When, 
                .protect = FALSE)
```

# Skills

```{r}

tribble(
  ~ Group, ~ List,
  "Programming", "R, Python, SQL, git, AWS, and Linux shell languages",
  "GIS", "QGIS, ArcGIS, GDAL/OGR, PostGIS, Google Earth Engine, and the R spatial ecosystem"
  ) %>% 
brief_entries(List, Group, .protect = FALSE)
```
