---
name: Lucas
surname: Johnson, Ph.D.
# position: "Ph.D. Candidate"
# address: "State University of New York College of Environmental Science and Forestry"
phone: +1 315-345-4713
www: lucaskjohnson.com
email: lucas.k.johnson03@gmail.com
# twitter: lucaskjohnson03
github: lucas-johnson
linkedin: lucaskjohnson
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::moderncv:
    theme: banking
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)

# Copied code from Mike Mahoney
make_detailed_section <- function(..., order = c(3, 2, 1, 4), detailVector = "Details", bulletVector = "Bullets", protect = TRUE) { 
  args <- list(...)
  if (length(args) == 0) stop("Function requires arguments")
  
  for (i in length(args)) {
    if (!is.list(args[[i]])) stop(paste("Argument", i, "is not a list."))
  }
  
  df <- vector("list")
  
  for(i in 1:length(args)) {
    df[[i]] <- tibble(
      What = args[[i]][[detailVector]][[order[[1]]]], 
      When = args[[i]][[detailVector]][[order[[2]]]], 
      With = args[[i]][[detailVector]][[order[[3]]]], 
      Where = args[[i]][[detailVector]][[order[[4]]]], 
      Why = args[[i]][[bulletVector]][seq_along(args[[i]][[bulletVector]])]
    )
  }
  
  do.call(rbind.data.frame, df) %>%
    detailed_entries(What, When, With, Where, Why, .protect = protect)
  
}
```


# Work Experience
```{r}
OSU <- vector("list")
OSU$Details <- c("Postdoctoral Scholar", "August 2024 - Present", "Oregon State University", "Riverdale, UT")
OSU$Bullets <- c(
  "Developed a shiny-live web map to support the joint consideration of carbon benefits and albedo offsets in tree-planting projects across the conterminous United States",
  "Decomposing Nepal-wide forest carbon trends with NASA GEDI data to distribute REDD+ payments"
)

CAFRI <- vector("list")
CAFRI$Details <- c("Research Assistant", "August 2019 - August 2024", "Climate and Applied Forest Research Institute", "Syracuse, NY")
CAFRI$Bullets <- c(
  "Developed a forest carbon mapping framework for the NYS DEC supporting net-zero emissions goals",
  "Communicated research findings in 4 scientific manuscripts and 8 conference presentations",
  "Contributed writing, code, and statistical/spatial analysis to technical reports for external collaborators",
  "Implemented R workflows to process > 30 TB of LiDAR point clouds and ~2 TB of Landsat imagery",
  "Established cloud computing infrastructure (AWS), geospatial databases, and data sharing software", 
  "Provided mentorship and technical support to grad students"
)

LK <- vector("list")
LK$Details <- c("Data Engineer", "August 2017 - July 2019", "Lightkeeper, LLC", "Boston, MA")
LK$Bullets <- c(
  "Refactored ETL pipeline, establishing best practices and standard tools for customer-specific scripts",
  "Designed and developed internal tools to track feature usage and identify computational bottlenecks",
  "Implemented slack integrations to streamline requests from client support team"
)

make_detailed_section(
  OSU,
  CAFRI,
  LK
)
```

# Education

```{r education}
esf <- vector("list")
esf$Details <- c("Doctor of Philosophy in Environmental Science", 
                 "August 2019 - May 2024", 
                 "SUNY College of Environmental Science and Forestry", 
                 "Syracuse, NY")
esf$Bullets <- c(
  NA
)

tufts <- vector("list")
tufts$Details <- c("Bachelor of Science in Computer Science", 
                   "August 2013 - May 2017",
                   "Tufts University", 
                   "Medford, MA")
tufts$Bullets <- c(NA)

make_detailed_section(esf, tufts)

```

# Volunteer Positions

```{r}
code_for_btv <- vector("list")

code_for_btv$Details <- c("Technical Lead: Courtbot project", "July 2020 - July 2021", "Code for Burlington", "Remote")
code_for_btv$Bullets <- c(
  NA
)

workshops <- vector("list")
workshops$Details <- c("Workshop Assistant", "December 2022, 2023", "Foundations of Scientific Computing", "Syracuse, NY")
# workshops$Bullets <- c("Provided technical support for workshop attendees")
workshops$Bullets <- c(NA)

make_detailed_section(code_for_btv, workshops)
# make_detailed_section(code_for_btv)
```

# Skills

```{r}

tribble(
  ~ Group, ~ List,
  "Programming", "R, Python, SQL, git, AWS, and Linux shell languages",
  "GIS", "QGIS, ArcGIS, GDAL/OGR, PostGIS, Google Earth Engine, and the R spatial ecosystem"
  ) %>% 
brief_entries(List, Group, .protect = FALSE)
```
